version: '3'

services:
  web:
    image: comdockerdevenvironmentscode-web
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
